//
//  Copyright © FINN.no AS.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

import UIKit

private class BundleHelper {
}

extension UIImage {
    convenience init(named imageAsset: ImageAsset) {
        #if SWIFT_PACKAGE
        let bundle = Bundle.module
        #else
        let bundle = Bundle(for: BundleHelper.self)
        #endif
        self.init(named: imageAsset.rawValue, in: bundle, compatibleWith: nil)!
    }

    @objc class func assetNamed(_ assetName: String) -> UIImage {
        #if SWIFT_PACKAGE
        let bundle = Bundle.module
        #else
        let bundle = Bundle(for: BundleHelper.self)
        #endif
        return UIImage(named: assetName, in: bundle, compatibleWith: nil)!
    }
}

//swiftlint:disable superfluous_disable_command
//swiftlint:disable type_body_length
enum ImageAsset: String {
    case adsenseDemo
    case avatar
    case bapShippable
    case betaImageSearch
    case blinkRocketMini
    case boat
    case buyingTipsCat
    case buyingTipsDog
    case car
    case checkCircleFilled
    case classifieds
    case consentTransparencyImage
    case cross
    case dissatisfiedFace
    case distance
    case emptyStateSaveSearch
    case favoriteActive
    case favorites
    case favouriteAdded
    case filter
    case finnLogoLarge
    case finnLogoSimple
    case gift
    case heartEmpty
    case home
    case iconRealestateApartments
    case iconRealestateBedrooms
    case iconRealestateOwner
    case iconRealestatePrice
    case jobs
    case mc
    case messages
    case mittanbud
    case moteplassen
    case notifications
    case notificationsBell
    case npCompare
    case npDrive
    case npHouseWeather
    case npPublicTransport
    case npRecommended
    case npSafeNeighborhood
    case npSchool
    case npStopwatch
    case npStore
    case npWalk
    case nyhetsbrevFraFinn
    case okonomi
    case playVideo
    case plus
    case primingFavoritesComments
    case primingFavoritesSearch
    case primingFavoritesSharing
    case profile
    case ratings
    case realestate
    case remove
    case savedSearches
    case search
    case service
    case shopping
    case sold
    case travel
    case vehicles
    case vippsLogo
    case virtualViewing
    case warranty
    case webview
    case wrench
    case yourads

    static var imageNames: [ImageAsset] {
        return [
            .adsenseDemo,
            .avatar,
            .bapShippable,
            .betaImageSearch,
            .blinkRocketMini,
            .boat,
            .buyingTipsCat,
            .buyingTipsDog,
            .car,
            .checkCircleFilled,
            .classifieds,
            .consentTransparencyImage,
            .cross,
            .dissatisfiedFace,
            .distance,
            .emptyStateSaveSearch,
            .favoriteActive,
            .favorites,
            .favouriteAdded,
            .filter,
            .finnLogoLarge,
            .finnLogoSimple,
            .gift,
            .heartEmpty,
            .home,
            .iconRealestateApartments,
            .iconRealestateBedrooms,
            .iconRealestateOwner,
            .iconRealestatePrice,
            .jobs,
            .mc,
            .messages,
            .mittanbud,
            .moteplassen,
            .notifications,
            .notificationsBell,
            .npCompare,
            .npDrive,
            .npHouseWeather,
            .npPublicTransport,
            .npRecommended,
            .npSafeNeighborhood,
            .npSchool,
            .npStopwatch,
            .npStore,
            .npWalk,
            .nyhetsbrevFraFinn,
            .okonomi,
            .playVideo,
            .plus,
            .primingFavoritesComments,
            .primingFavoritesSearch,
            .primingFavoritesSharing,
            .profile,
            .ratings,
            .realestate,
            .remove,
            .savedSearches,
            .search,
            .service,
            .shopping,
            .sold,
            .travel,
            .vehicles,
            .vippsLogo,
            .virtualViewing,
            .warranty,
            .webview,
            .wrench,
            .yourads,
    ]
  }
}
